os: osx
before_install:
- brew update
- brew tap homebrew/versions
- brew unlink node
- brew install node5 # Prerequest for test.
install:
- npm install
script:
- npm run test:cov
after_script:
- if [[ `node --version` == *v4* ]]; then cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter;
  fi
env:
  global:
  - secure: KN/tbbXnFJ/52E1d7wM1KHzUgS8iP1VW/w0uWRp4Y2XE37G3w/sxORtO6Lqq7af0tHXFzrCXWiK6wrdti8ux0Y/JUA9AC3WgRsMq3LILL9qLCmZ10cLcpd7RzbAF1ul/7yqaTdLsEZLlsict5MUZY67+I8yKi1glzXIHZqGDo3SQ+MSrUi3FDbHN2orVs8a8/vp/Vai7mIEy07hf+vrlFVDv1YAbjB5PggO5gLTD3KPdWXlEROai513Ee4xODdxAsYpj8n7UmgvgOOZqkO8WC7kDKsljfqqKUkCA7BcRkN8UdWvsI5tksq7Sfngk9H0M3aQsKrMk4EVYVVQP2t96ERWeaQ4iTY56rRif8xX/GhtmZCgn4ETPl6nfB3p/LG41sI53zWf15oecEnm0wJ1Zm7PDXtIfpc5jNvJCZzlwLkytSXgx/q/Xowztv4NqarBxBd1hkq5cSxFQjR0ebBDgYFkikQ3VjzjvDA+7pMQfHCuSKKONKF1XZ+O2WAxLSgb9/fhT5JOPWzExnLO7NmqhA2h5IMTb5eLonsVDRv7eige7ay6Ehou4/9WrNsOQ4qGcXT0CbKbug2Ii56krYPFeqdteqJbHd2busN2S235praDkffWGYLkUf06haIabTMpXjz9p36do4KxOnvvIU5qKiiDAnBldqPLs3erV1IMNtu4=
  - secure: c0VKH7ZclULFdoq8lUKfHTH69XR8J/nf+3Kulo6lpuDLZVVrXo34PkG07okoRzfodV2Tdd+TSilqE2d25PBFfZVRrbH7MZGpOsuUTtw1RU7yEkyK0qIUTOVeYZ5BxigNf3iHsu8uLI0qnJSM3zamcbLjb5Z3ck3fLZeALB/WakSICzSHkJNsL2DGeYuckVg7kxAkHRViwfGInDAY1595RX5T3NoOsGsz9xf7Fws/2/GB7Cd6IDE3Isnc4wTNZDQ2yzCDYYdwW0WAMJUulNlW/q61pIBgt+zE8eTsO4eZDbwWCssS0fP59XQS88Nkh+ch61CPWFE6bFFFh68zvRm5LJkl2zXWzvBHrw6mffrFn3A1EF/+JmP89nUIFaJTRAsymxfetI6RPf13BpY1iTOVNe4Wg5R85CqoCviVWRSiTDzL5AEQw7+F5ZK7U/ptWjGGFwkVJqI2KYFrVw8vsFtsMuFU8Hp8bgc5UFpPOzKTt38DG8b7BAssitg+gBtBiCtYLw2ZHDAPwb3mLwKIRxLFV2tMDtpvUmp0h7wi6hN9/5255egoacOMQWBTr3u3FxDthiFCQbx6lNNDKm4qYOupxP9E1hxYGYmCOA0AkgtDDiTp7Q2lXcL5x7a6XK1drvz6o3nTd4ZjsCs3wcqg+2WkRTbYcGjZeMuHF/x/sRMhFDQ=
