language: node_js
node_js:
- '4'
script:
- npm run test:cov
after_script:
- if [[ `node --version` == *v4* ]]; then cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter;
  fi
env:
  global:
    secure: KN/tbbXnFJ/52E1d7wM1KHzUgS8iP1VW/w0uWRp4Y2XE37G3w/sxORtO6Lqq7af0tHXFzrCXWiK6wrdti8ux0Y/JUA9AC3WgRsMq3LILL9qLCmZ10cLcpd7RzbAF1ul/7yqaTdLsEZLlsict5MUZY67+I8yKi1glzXIHZqGDo3SQ+MSrUi3FDbHN2orVs8a8/vp/Vai7mIEy07hf+vrlFVDv1YAbjB5PggO5gLTD3KPdWXlEROai513Ee4xODdxAsYpj8n7UmgvgOOZqkO8WC7kDKsljfqqKUkCA7BcRkN8UdWvsI5tksq7Sfngk9H0M3aQsKrMk4EVYVVQP2t96ERWeaQ4iTY56rRif8xX/GhtmZCgn4ETPl6nfB3p/LG41sI53zWf15oecEnm0wJ1Zm7PDXtIfpc5jNvJCZzlwLkytSXgx/q/Xowztv4NqarBxBd1hkq5cSxFQjR0ebBDgYFkikQ3VjzjvDA+7pMQfHCuSKKONKF1XZ+O2WAxLSgb9/fhT5JOPWzExnLO7NmqhA2h5IMTb5eLonsVDRv7eige7ay6Ehou4/9WrNsOQ4qGcXT0CbKbug2Ii56krYPFeqdteqJbHd2busN2S235praDkffWGYLkUf06haIabTMpXjz9p36do4KxOnvvIU5qKiiDAnBldqPLs3erV1IMNtu4=
